Obstacle course second
kennedyrobotics1/RoadRunnerOffseason pull request #10
Opened 2024-09-04 23:32 UTC by atra-ment

My code tells the robot to back up after trucking the tower, turns 90 degrees to the left, and goes forward, stopping before the blue alliance wall.
Start point - (5, 10, 0°)
End point - (-10, 55, 90°)
<img width="596" alt="Screenshot 2024-09-04 163206" src="https://github.com/user-attachments/assets/94696044-4e2f-4635-a9e0-80e1cee1cce5">

2024-09-04 23:44 UTC, CharlesJfkRbt approved these changes

2024-09-04 23:58 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/kevinaPath.java
> +
Removing this space will keep the code tidy. Just a tip Mr. Hernandez gave me.

2024-09-04 23:59 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/kevinaPath.java
> +public class kevinaPath extends LinearOpMode {
Should not be named after you

2024-09-05 00:10 UTC, CubeOfCheese requested changes

2024-09-05 00:10 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/kevinaPath.java
You should delete this file now

2024-09-05 00:20 UTC, CubeOfCheese approved these changes

2024-09-05 00:46 UTC, CubeOfCheese approved these changes

2024-09-05 00:49 UTC, merged