Obstacle course fourth
kennedyrobotics1/RoadRunnerOffseason pull request #11
Opened 2024-09-04 23:44 UTC by atra-ment

My code turns 90 degrees to the right, moves forward in a diagonal line to in front of the truss, and moves forward in a straight line under the truss.
Start point (-9, 59, 0°)
End point (-5, -30, 270°)
<img width="595" alt="Screenshot 2024-09-04 163847" src="https://github.com/user-attachments/assets/addd6188-65d4-4508-8f11-6dfeae803a2a">

2024-09-04 23:46 UTC, CharlesJfkRbt approved these changes

2024-09-04 23:55 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/obstacleCoursePathFour.java
> +
Put the annotation directly above the function

2024-09-04 23:57 UTC, CubeOfCheese requested changes

2024-09-04 23:57 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/obstacleCoursePathFour.java
> +public class obstacleCoursePathFour extends LinearOpMode {
put annotation directly above the class

2024-09-05 00:01 UTC, AkithMadurapperuma commented
My end point coordinates are (-10, 55) but your starting point in this code is (-9, 59). You should probably update your code since my chunk is before this one.

2024-09-06 23:48 UTC, isabellammjfk reviewed
lowk a dub but keeping it real and good job queen

2024-09-06 23:48 UTC, isabellammjfk commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/ObstacleCoursePath.java
> +                .lineToSplineHeading(new Pose2d(-5, 30, Math.toRadians(270)))
is there meant to be a duplicate??

2024-09-06 23:48 UTC, isabellammjfk commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/ObstacleCoursePath.java
> +        // fourth part
you should also have comments to differentiate between when each part is being called at the bottom

2024-09-06 23:52 UTC, CubeOfCheese approved these changes

2024-09-06 23:52 UTC, isabellammjfk approved these changes
muy biennnnnnnnnnnn

2024-09-06 23:53 UTC, merged