Autonomous path 3rd
kennedyrobotics1/RoadRunnerOffseason pull request #3
Opened 2024-05-31 23:32 UTC by isabellammjfk

este es la terced  tradectoria

2024-05-31 23:33 UTC, CubeOfCheese requested changes

2024-05-31 23:33 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/PracticePathTestRoadRunner.java
You need to add your code to the FinalPath file. Not create a new separate file

2024-06-01 00:01 UTC, atra-ment approved these changes

2024-06-01 00:02 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/PracticePathTestRoadRunner.java
You should delete this file now

2024-06-01 00:09 UTC, atra-ment approved these changes

2024-06-01 00:15 UTC, CubeOfCheese approved these changes

2024-06-01 00:16 UTC, merged