Obstecle course first
kennedyrobotics1/RoadRunnerOffseason pull request #6
Opened 2024-08-31 01:58 UTC by OLeg25685

1- go forward from start point (-60, 60, 270 degrees)
2- turn along the arc 
3- parking on coordinates (7.5,12, 0 degrees))
![image](https://github.com/user-attachments/assets/e1fc3afa-06ad-45cb-8f0d-e478d6d1a6a4)

2024-08-31 02:07 UTC, CubeOfCheese requested changes

2024-08-31 02:07 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/OlehPath.java
> +
get rid of the extra lines

2024-08-31 02:07 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/OlehPath.java
> +public class OlehPath extends LinearOpMode{
Don't name the class or file after yourself. It should be named something like ObstacleCoursePath

2024-08-31 02:07 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/OlehPath.java
> +        drive.setPoseEstimate(new Pose2d(-60, 60,Math.toRadians(270)));
space after comma please
```suggestion
        drive.setPoseEstimate(new Pose2d(-60, 60, Math.toRadians(270)));
```

2024-08-31 02:07 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/OlehPath.java
> +public class OlehPath extends LinearOpMode{
space before curly brace please
```suggestion
public class OlehPath extends LinearOpMode {
```

2024-08-31 02:28 UTC, isabellammjfk approved these changes
looks good and it works!

2024-08-31 02:28 UTC, CubeOfCheese approved these changes

2024-09-05 00:36 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/ObstacleCoursePath.java
> +                .splineTo(new Vector2d(7.5, 12), Math.toRadians(0))
Kevina's code (2nd Chunk) starts at (5, 10) while yours ends at (7.5, 12). This should be fixed.

2024-09-06 23:42 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/ObstacleCoursePath.java
> +
Get rid of these extra lines

2024-09-07 00:16 UTC, isabellammjfk reviewed
good job!!

2024-09-07 00:16 UTC, isabellammjfk commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/ObstacleCoursePath.java
> +        drive.followTrajectory(trajectoryFirstPart);
maybe change the trajectory names of your path to match where you're going on the field

2024-09-07 02:11 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/ObstacleCoursePath.java
> +        drive.setPoseEstimate(new Pose2d(5, 10, Math.toRadians(0)));
We should only have one setPoseEstimate

2024-09-07 02:28 UTC, atra-ment commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/ObstacleCoursePath.java
Be consistent with spaces between each part--either add empty line before each comment for the trajectory parts or delete empty lines

2024-09-07 02:28 UTC, atra-ment commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/ObstacleCoursePath.java
> +        // first chunk
If empty lines were added between the trajectory parts, consider adding spaces between the calling of the trajectory parts here.

2024-09-07 02:32 UTC, atra-ment approved these changes

2024-09-07 02:33 UTC, CubeOfCheese approved these changes

2024-09-07 02:34 UTC, merged