Obstacle course fifth
kennedyrobotics1/RoadRunnerOffseason pull request #7
Opened 2024-09-03 23:44 UTC by isabellammjfk

so basically the robot moves towards the wall, turns, goes forward, then goes forward to yeet 16177 out of the way to park, ending the obstacle course 

starting position: (-5, -30) 
ending position: (40,-35) 
![Screenshot 2024-09-03 164348](https://github.com/user-attachments/assets/15e7aabf-5e9a-4f19-8c18-4ffcf2ebd023)

2024-09-03 23:57 UTC, OLeg25685 commented
Gooood work! if do little cleaning in code it will look perfect.

2024-09-04 00:17 UTC, OLeg25685 requested changes
There is little trouble for my eyes

2024-09-04 00:17 UTC, OLeg25685 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/izzyPath.java
> +
Why there doing this space?

2024-09-04 00:17 UTC, OLeg25685 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/izzyPath.java
> +}
All else code is cool

2024-09-04 00:17 UTC, OLeg25685 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/izzyPath.java
> +        //
What and why there those comment, where is comment?

2024-09-04 00:21 UTC, merged

2024-09-04 00:27 UTC, CubeOfCheese requested changes

2024-09-04 00:27 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/izzyPath.java
Your file should not be named after you. It should be named ObstacleCoursePath.java

2024-09-04 00:27 UTC, CubeOfCheese commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/izzyPath.java
> +        Trajectory forwardToWall= drive.trajectoryBuilder(new Pose2d(-5, -30, Math.toRadians(270)))
space before equal sign plz
```suggestion
        Trajectory forwardToWall = drive.trajectoryBuilder(new Pose2d(-5, -30, Math.toRadians(270)))
```

2024-09-04 00:30 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/izzyPath.java
> +}
GOOD!

2024-09-04 00:30 UTC, AkithMadurapperuma commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/drive/opmode/izzyPath.java
> +
GREAT!